# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - 
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
    
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Visual Studio Enterprise Subscription – MPN(727569fb-5294-4ca5-9005-466abf5d33f1)'
    backendAzureRmResourceGroupName: 'myapp'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan